### ISSUE TITLE
Code missing?

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/WordPress-Complete-Sixth-Edition#1]
In chapter 'Developing Your Own Theme'  author says about downloading corresponding code for three times. Especially there is a phrase: '_This version of the index.php file is available in the code bundle for this
chapter--inside a sub folder labeled phase 2_'. I can not see any 'phase2' folders or 'index.php' files here.

**Comment by praju89** [comment]
Hello,
This information box seems redundant as the code from this chapter can be run directly by copy/pasting it in any editor and the author hasn't provided the code bundle for this particular chapter. Also, that index.php file is going to contain the main design's HTML file, which you can find at the very beginning of the chapter.
